dist: trusty
sudo: required
language: c
compiler:
- clang
- gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libreadline-dev

script:
- ./autogen.sh
- ./configure
- make check
