os:
- linux
- osx

dist: trusty
addons:
  apt:
    packages:
    - libreadline-dev
language: c
compiler:
- clang
- gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

script:
- ./autogen.sh
- ./configure
- make check
